IMPLMODULESRCS = Strings_Cstring_Mod.F90
IMPLSRCS = Strings_Cstring_Impl.F90
IORHDRS = Strings_Cstring_IOR.h Strings_IOR.h
IORSRCS = Strings_Cstring_IOR.c
SKELSRCS = Strings_Cstring_fSkel.c
STUBHDRS = Strings_Cstring_fAbbrev.h Strings_Cstring_fStub.h
STUBMODULESRCS = Strings_Cstring.F90
STUBSRCS = Strings_Cstring_fStub.c
TYPEMODULESRCS = Strings_Cstring_type.F90
