#!/bin/sh
# File:        runPy2C
# Copyright:   (c) 2001 Lawrence Livermore National Security, LLC
# Description: Set environment variables and run python
# Revision:    $Revision$
# Date:        $Date$
#

case "`uname`" in
  CYGWIN*) cygwin=true;;
  *) cygwin=false;;
esac

PYTHONLIB=../../../runtime/sidl/.libs
PYTHONPATH=../../../runtime/python
SIDL_DLL_PATH="../libC/libImpl.scl"
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PYTHONLIB
export PYTHONPATH SIDL_DLL_PATH LD_LIBRARY_PATH

if $cygwin; then
  PATH=$PATH:$PYTHONLIB
  export PATH
fi

python helloclient.py
