<?xml version="1.0"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="html" doctype-public='-//W3C//DTD HTML 4.0 TRANSITIONAL//EN"' doctype-system="http://www.w3c.org/TR/REC-html40/loose.dtd"/>
    
    <xsl:variable name="newline">
    <xsl:text>  
    </xsl:text>
    </xsl:variable>
   
   <xsl:template match="/">
            <xsl:apply-templates select="Library"/>
            
    </xsl:template>  
    
    
    <xsl:template match="Library">
        <html> 
            <head>
                <xsl:call-template name="generateFileHeader">
                    <xsl:with-param name="date" select="@date"/>
                    <xsl:with-param name="title">Main Page</xsl:with-param>
                </xsl:call-template>    
            </head>
                <xsl:choose>
                    <xsl:when test="count(Package) &gt; 0">
                
                        <xsl:value-of select="$newline"/>
                     
                    <FRAMESET cols="20%,80%">
                            <FRAME src="allclasses-frame.html" name="packageFrame"/>
                         
                            <FRAME src="package-summary.html" name="classFrame"/>
                     
                    </FRAMESET>
                    <NOFRAME>
                        <p> This document was designed for frames. However you may view the documentation on the following</p><br/>
                        
                        <a href="package-summary.html" >Non-Frame version</a>
                           
                    </NOFRAME>
                    </xsl:when>
                    <xsl:otherwise>
                        <FRAMESET cols="100%">
                            <Frame src="allclasses-noframe.html.html" name="classFrame"/>
                        </FRAMESET>
                        <NOFRAME>
                            <p> This document was designed for frames. However you may view the documentation on the following</p><br/>
                            <a href="allclasses-noframe.html.html" >Non-Frame version</a>
                        </NOFRAME>
                    </xsl:otherwise>
                </xsl:choose>
                  
                                       
        </html>    
    </xsl:template>
        
        
    <xsl:template name="generateFileHeader">   
            <xsl:param name="date"/>   
            <xsl:param name="title"/>  
        
            <xsl:call-template name="generateDateStamp">  
                <xsl:with-param name="printDate" select="$date"/>
            </xsl:call-template> 
            <title><xsl:value-of select="$title"/></title> 
                
        </xsl:template>
    <xsl:template name="generateDateStamp">
        <xsl:param name="printDate"/>
        <xsl:value-of select="$newline"/>
        <xsl:comment>Generated by babeldoc on <xsl:value-of select="$printDate"/> </xsl:comment>
        <xsl:value-of select="$newline"/>
    </xsl:template> 
        
</xsl:stylesheet>

